UniversityRegistrar/Models/Course.cs
using System;
using System.Collections.Generic;

namespace UniversityRegistrar.Models
{
    public class Course
    {
        public Course()
        {
            this.Students = new HashSet<CourseStudent>();
        }

        public int CourseId { get; set; }

        public string Name { get; set; }

        public int CourseNumber { get; set; }

        public ICollection<CourseStudent> Students { get; }
    }
}

UniversityRegistrar/Models/CourseStudent.cs
namespace UniversityRegistrar.Models
{
    public class CourseStudent
    {
        public int CourseStudentId { get; set ;}

        public int StudentId { get; set ;}

        public int CourseId { get; set ;}

        public Student Student { get; set ;}

        public Course Course { get; set ;}

    }

}

UniversityRegistrar/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContextFactory : IDesignTimeDbContextFactory<UniversityRegistrarContext>
  {
    UniversityRegistrarContext IDesignTimeDbContextFactory<UniversityRegistrarContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<UniversityRegistrarContext>();
      var connectionString = configuration.GetConnectionString("DefaultConnection");

      builder.UseMySql(connectionString);

      return new UniversityRegistrarContext(builder.Options);
    }
  }
}

UniversityRegistrar/Models/Student.cs
using System.Collections.Generic;
using System;

namespace UniversityRegistrar.Models
{
    public class Student
    {
        public Student()
        {
            this.Courses = new HashSet<CourseStudent>();
        }

        public int StudentId { get; set; }

        public string Name { get; set; }

        public DateTime Date { get; set; }

        public ICollection<CourseStudent> Courses { get; }
    }
}

UniversityRegistrar/Models/UniversityRegistrarContext.cs
using Microsoft.EntityFrameworkCore;

namespace UniversityRegistrar.Models
{
  public class UniversityRegistrarContext : DbContext
  {
    public virtual DbSet<Student> Students { get; set; }
    public DbSet<Course> Courses { get; set; }
    public DbSet<CourseStudent> CourseStudent { get; set; }

    public UniversityRegistrarContext(DbContextOptions options) : base(options) { }
  }
}

UniversityRegistrar/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UniversityRegistrar.Models;


namespace UniversityRegistrar.Controllers
{
    public class CourseController : Controller
    {
        private readonly UniversityRegistrarContext _db;

        public CourseController(UniversityRegistrarContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Courses.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Course course)
        {
            _db.Courses.Add(course);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Course theCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
            return View(theCourse);
        }
    }
}

UniversityRegistrar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UniversityRegistrar.Models;

namespace UniversityRegistrar.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

UniversityRegistrar/Controllers/StudentController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using UniversityRegistrar.Models;


namespace UniversityRegistrar.Controllers
{
    public class StudentController : Controller
    {
        private readonly UniversityRegistrarContext _db;

        public StudentController(UniversityRegistrarContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Students.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Student student)
        {
            _db.Students.Add(student);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Student theStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
            return View(theStudent);
        }

        public ActionResult Edit(int id)
        {
            var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
            ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
            return View(thisStudent);
        }

        [HttpPost]
        public ActionResult Edit(Student student, int CourseId)
        {
            if (CourseId != 0)
            {
                _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
            }
            _db.Entry(student).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

UniversityRegistrar/Views/Course/Create.cshtml
@{
    Layout = "_Layout";
}
@model UniversityRegistrar.Models.Course;

<h1>Add course</h1>
<div class="info-container">
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name) <br><br>

    @Html.LabelFor(model => model.CourseNumber)
    @Html.TextBoxFor(model => model.CourseNumber)<br><br>

    <input type="submit" value="Add Course" class="btn btn-info" />

}
</div>

<p>@Html.ActionLink("Back to course list", "Index", "Course")</p>
<p>@Html.ActionLink("Go Home", "Index", "Home")</p>

UniversityRegistrar/Views/Course/Details.cshtml
@{
    Layout = "_Layout";
}
@model UniversityRegistrar.Models.Course;

<div class="info-container">
    <h1>@Model.Name @Html.DisplayFor(model => model.CourseNumber)</h1>
    <hr />
    @if(Model.Students.Count == 0)
    {
        <p>Any students haven't enrolled this course yet.</p>
    }
    else
    {
        @foreach(var join in Model.Students)
        {
            <li>@join.Course.Name</li>
        }
    }
</div>

<p>@Html.ActionLink("Back to course list", "Index")</p>
<p>@Html.ActionLink("Go Home", "Index", "Home")</p>

UniversityRegistrar/Views/Course/Index.cshtml
@{
    Layout = "_Layout";
}
@using UniversityRegistrar.Models;

<h1>List of Students</h1>
<div class="info-container">
    @if(Model.Count == 0)
    {
        <h5>You haven't added any courses, click the link below to add one.</h5>
    }
    <ul>
    @foreach (Course course in Model)
    {
        <li>@Html.ActionLink($"{course.Name}", "Details", new { id = course.CourseId })</li>
        <hr />
    }
    </ul>
</div>

<p>@Html.ActionLink("Add a new course", "Create")</p>
<p>@Html.ActionLink("Go Home", "Index", "Home")</p>

UniversityRegistrar/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

<h1>Welcome Registrar!</h1>

<h3>Navigate through the links below</h3>

<p>@Html.ActionLink("See a list of students", "Index", "Student")<p>
<p>@Html.ActionLink("Add a new student to the registry", "Create", "Student")</p>
<p>@Html.ActionLink("See a list of courses", "Index", "Course")</p>
<p>@Html.ActionLink("Add a new course to the registry", "Create", "Course")</p>


UniversityRegistrar/Views/Shared/Footer.cshtml
<footer>Happily handmade in Seattle with love and coffee &#9400;2020 Misaki Koonce</footer>

UniversityRegistrar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Student Registrar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
      @RenderBody()
    </div>
    @Html.Partial("Footer")
  </body>
</html>

UniversityRegistrar/Views/Student/Create.cshtml
@{
    Layout = "_Layout";
}
@model UniversityRegistrar.Models.Student;
@using System;

<h1>Add student</h1>
<div class="info-container">
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)<br><br>

    @Html.Hidden("Date", DateTime.Now)
    @Html.Label("Select a course")
    @Html.DropDownList("CourseId")<br><br>

    <input type="submit" value="Add Student" class="btn btn-info" />
}
</div>

<p>@Html.ActionLink("Back to the list of stidents", "Index", "Course")</p>
<p>@Html.ActionLink("Go Home", "Index", "Home")</p>

UniversityRegistrar/Views/Student/Details.cshtml
@{
    Layout = "_Layout";
}
@model UniversityRegistrar.Models.Student;

<div class="info-container">
    <h1>@Model.Name</h1>

    <h3>Enrolled on @Model.Date</h3>

    @if(Model.Courses.Count == 0)
    {
        <p>This student isn't enrolled in any classes yet.</p>
    }

    @foreach(var join in Model.Courses)
    {
        <li>@join.Course.Name</li>
    }
</div>

<p>@Html.ActionLink("Back to student list", "Index")</p>
<p>@Html.ActionLink("Edit info", "Edit", new { id = Model.StudentId})</p>
<p>@Html.ActionLink("Go Home", "Index", "Home")</p>

UniversityRegistrar/Views/Student/Edit.cshtml
@{
    Layout = "_Layout";
}
@model UniversityRegistrar.Models.Student;

<h1>Edit</h1>
<div class="info-container">
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)<br><br>

    @Html.HiddenFor(model => model.StudentId)
    @Html.Label("Select a course")
    @Html.DropDownList("CourseId")<br><br>

    <input type="submit" value="Edit" class="btn btn-info" />
}
</div>

<p>@Html.ActionLink("Back to student list", "Index")</p>
<p>@Html.ActionLink("Go Home", "Index", "Home")</p>

UniversityRegistrar/Views/Student/Index.cshtml
@{
    Layout = "_Layout";
}
@using UniversityRegistrar.Models;

<h1>List of Students</h1>

<div class="info-container">
    @if(Model.Count == 0)
    {
        <h5>You haven't added any students, click the link below to add one.</h5>
    }

    <ul>
    @foreach (Student student in Model)
    {
        <li>@Html.ActionLink($"{student.Name}", "Details", new { id = student.StudentId })</li>
        <hr />
    }
    </ul>
</div>

<p>@Html.ActionLink("Add a new student", "Create")</p>
<p>@Html.ActionLink("Go Home", "Index", "Home")</p>